name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node: [lts/*, lts/-1]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Install Global Packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: npm i -g publint @arethetypeswrong/cli knip

      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: nr lint

      - name: Type check
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: nr typecheck

      - name: Build
        run: nr build

      - name: Test
        run: nr test

      - name: Pub Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: publint

      - name: Are The Types Wrong
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: attw --pack .

      - name: Dedupe
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm dedupe --check

      - name: Knip
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: knip
